### ISSUE TITLE
typo in paper?

### ISSUE THREAD

**Issue by KylinA1** [xinshi-chen/GenerativeAdversarialUserModel#3]
1.
in euqation(5), 

`min_{\theta} max_{\alpha}`
should be 
`min_{\alpha} max_{\theta}`

is that correct?
2. 
in equation right below equation(4)
`b` and `b^\prime` in `r(s, a)` is `l` instead of `dn+d`?

**Comment by xinshi-chen** [comment]
Thank you for the careful reading!

1.
The equation(5) in the paper is correct. the maximization over alpha corresponds to the user who is maximizing her own reward. The minimization over theta is the discriminator that wants to give higher rewards to the 'true actions' in the data.

2.
Yes, this is a typo! we have fixed it in the arxiv version https://arxiv.org/pdf/1812.10613.pdf
